train:
  Resize:
    - 256
    - 256
  CenterCrop: 224
  ColorJitter:
  RandomRotation: 90
  RandomHorizontalFlip:
  RandomVerticalFlip:
  ToTensor:
  RandomErasing:

val:
  Resize:
    - 224
    - 224
  ToTensor:

test:
  Resize:
    - 224
    - 224
  ToTensor: